# Generated by Django 3.0.2 on 2020-01-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axioms', '0002_auto_20200105_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
